// Single source of truth for the component catalog. Nav, search, filters,
// cards, and component-page metadata all derive from this. Preview React
// components are mapped by `id` in app/_previews (kept separate so this module
// stays serializable and importable from Server Components).
import { product, installCommand } from "./product";

export type CategoryId =
  | "ai"
  | "developer-tools"
  | "collaboration"
  | "data-motion"
  | "mobile"
  | "commerce"
  | "file"
  | "security"
  | "communication"
  | "productivity"
  | "animated-shadcn"
  | "text"
  | "creative"
  | "backgrounds"
  | "product-backgrounds"
  | "workflow-heroes"
  | "icons";

export type Access = "free" | "pro";
export type AnimationEngine = "motion" | "css" | "motion+radix";
export type Complexity = "simple" | "medium" | "complex";
/** Lightweight production status (docs/39). Absent = legacy sellability track. */
export type ReleaseStatus = "released" | "experimental";

export interface CatalogItem {
  id: string;
  name: string;
  slug: string;
  description: string;
  category: CategoryId;
  subcategory?: string;
  status: "stable" | "beta";
  access: Access;
  dependencies: string[];
  registryDependencies: string[];
  tags: string[];
  /** Registry item name → generates the install command + registry URL. */
  registryItem: string;
  documentationPath: string;
  dateAdded: string; // ISO date
  featured: boolean;
  supportsDarkMode: boolean;
  supportsReducedMotion: boolean;
  requiresClient: boolean;
  animationEngine: AnimationEngine;
  /** Preferred preview stage proportion. */
  stage: "text" | "canvas" | "icon" | "interactive" | "card";
  /** Rapid-track metadata (docs/39). Optional for legacy items. */
  complexity?: Complexity;
  releaseStatus?: ReleaseStatus;
  /** Catalog entry kind. Absent = "component". Blocks/packs are labeled distinctly. */
  kind?: "component" | "block" | "pack";
  /** For blocks/packs: the component slugs they compose (shown on cards + pages). */
  composes?: string[];

  /* --- Catalog presentation overrides (docs/55). All optional; resolvePresentation()
     fills category/kind/complexity defaults when absent. Individual items override. --- */
  /** Desktop preview size taxonomy → drives height strategy + default span. */
  previewSize?: PreviewSize;
  /** How the catalog card renders the component. Detail pages are always interactive. */
  previewMode?: PreviewMode;
  /** Interior surface tone. Coherent card chrome shared; only the surface tone varies. */
  stageFamily?: StageFamily;
  /** 12-column desktop span. */
  cardSpan?: CardSpan;
}

/** Preview-size taxonomy (docs/55 §3). */
export type PreviewSize = "small" | "standard" | "wide" | "full" | "mobile" | "ambient";
/** Catalog cards use "staged"/"ambient"; detail pages use "interactive". */
export type PreviewMode = "staged" | "interactive" | "ambient";
/** Controlled interior surface tones (docs/55 §5) — not one style per component. */
export type StageFamily =
  | "ai"
  | "console"
  | "collab"
  | "data"
  | "mobile"
  | "commerce"
  | "security"
  | "productivity"
  | "creative"
  | "editorial"
  | "neutral";
export type CardSpan = 4 | 6 | 8 | 12;

export interface Presentation {
  previewSize: PreviewSize;
  previewMode: PreviewMode;
  stageFamily: StageFamily;
  cardSpan: CardSpan;
  /** Mobile always collapses to a single full-width column. */
  mobileCardSpan: 12;
}

export interface Category {
  id: CategoryId;
  label: string;
  blurb: string;
}

export const categories: Category[] = [
  { id: "ai", label: "AI interfaces", blurb: "Streaming responses, agent runs, and AI product surfaces." },
  { id: "developer-tools", label: "Developer tools", blurb: "Pipelines, logs, inspectors, and dev workflows." },
  { id: "collaboration", label: "Collaboration", blurb: "Presence, activity, and multiplayer product motion." },
  { id: "data-motion", label: "Data motion", blurb: "KPIs, streaming rows, and dashboard state." },
  { id: "mobile", label: "Mobile interactions", blurb: "Swipe, gestures, and touch-first product patterns." },
  { id: "file", label: "File workflows", blurb: "Upload, queue, processing, and export motion." },
  { id: "commerce", label: "Commerce", blurb: "Variants, cart, checkout, and order motion." },
  { id: "security", label: "Security & accounts", blurb: "Passkeys, 2FA, sessions, and account safety flows." },
  { id: "communication", label: "Communication", blurb: "Messaging, delivery, presence, and threads." },
  { id: "productivity", label: "Productivity", blurb: "Boards, tasks, timelines, and bulk actions." },
  { id: "text", label: "Text animations", blurb: "Headline-grade text reveals and loops." },
  { id: "creative", label: "Creative UI", blurb: "Cards, lists, and interactive surfaces." },
  { id: "backgrounds", label: "Backgrounds", blurb: "Ambient, performance-safe backdrops." },
  { id: "product-backgrounds", label: "Product Backgrounds", blurb: "Animated backgrounds driven by application state - workflows, signals, queues, grids, contours, and events." },
  { id: "workflow-heroes", label: "Workflow Heroes", blurb: "Editable hero blocks that demonstrate a real product workflow." },
  { id: "animated-shadcn", label: "Animated shadcn", blurb: "Accessible Radix components with meaningful motion." },
  { id: "icons", label: "Animated icons", blurb: "Tiny motion for buttons and actions." },
];

const ADDED = "2026-07-14";

export const catalog: CatalogItem[] = [
  {
    id: "ai-response-stream",
    name: "AI Response Stream",
    slug: "ai-response-stream",
    description:
      "Streaming assistant response your app drives: text, code with copy, inline citations, and stop/retry/complete/error states.",
    category: "ai",
    subcategory: "AI interfaces",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["ai", "assistant", "streaming", "chat", "llm", "citations", "code"],
    registryItem: "ai-response-stream",
    documentationPath: "/components/ai-response-stream",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "deployment-pipeline",
    name: "Deployment Pipeline",
    slug: "deployment-pipeline",
    description:
      "Visualize a CI/CD run - stage status, running-stage emphasis, durations, expandable logs, and Retry on failed stages. Data is controlled by your app.",
    category: "developer-tools",
    subcategory: "Developer tools",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["ci", "cd", "pipeline", "deploy", "stages", "logs", "status", "retry", "devtools"],
    registryItem: "deployment-pipeline",
    documentationPath: "/components/deployment-pipeline",
    dateAdded: ADDED,
    featured: true,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "live-presence-stack",
    name: "Live Presence Stack",
    slug: "live-presence-stack",
    description:
      "A live avatar stack for collaborative apps - animated join/leave, per-user active/idle/editing/viewing status, overflow count, and a keyboard-accessible detail list.",
    category: "collaboration",
    subcategory: "Collaboration",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["presence", "avatars", "collaboration", "realtime", "multiplayer", "status"],
    registryItem: "live-presence-stack",
    documentationPath: "/components/live-presence-stack",
    dateAdded: ADDED,
    featured: true,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "kpi-number-morph",
    name: "KPI Number Morph",
    slug: "kpi-number-morph",
    description:
      "An animated KPI stat that morphs between values with a direction-aware, color-independent trend indicator. Controlled value, locale + compact formatting.",
    category: "data-motion",
    subcategory: "Data motion",
    status: "beta",
    access: "free",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["kpi", "metric", "number", "counter", "dashboard", "stat"],
    registryItem: "kpi-number-morph",
    documentationPath: "/components/kpi-number-morph",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "card",
    complexity: "simple",
    releaseStatus: "released",
  },
  {
    id: "tool-call-activity",
    name: "Tool Call Activity",
    slug: "tool-call-activity",
    description:
      "Presentation-only inspector for an agent's tool calls: concurrent calls, expandable details, inline approve/reject, retry, and compressed completed steps.",
    category: "ai",
    subcategory: "AI interfaces",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["ai", "agent", "tool calls", "activity", "approval", "status", "retry"],
    registryItem: "tool-call-activity",
    documentationPath: "/components/tool-call-activity",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "live-log-stream",
    name: "Live Log Stream",
    slug: "live-log-stream",
    description:
      "A live log console - auto-follow that never fights your scroll, a \"N new lines\" resume indicator, pause/resume, search, per-level filtering, copy, and bounded history. Data is controlled by your app.",
    category: "developer-tools",
    subcategory: "Developer tools",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["logs", "log", "terminal", "console", "streaming", "follow", "tail", "search", "filter", "devtools"],
    registryItem: "live-log-stream",
    documentationPath: "/components/live-log-stream",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "activity-stream",
    name: "Activity Stream",
    slug: "activity-stream",
    description:
      "A collaboration activity feed that goes beyond a dotted timeline - groups repeated actions, date separators, an unread divider, live-arriving items, and filtering by event type. Your app owns the events.",
    category: "collaboration",
    subcategory: "Collaboration",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["activity", "collaboration", "feed", "timeline", "unread", "grouping", "filter", "audit"],
    registryItem: "activity-stream",
    documentationPath: "/components/activity-stream",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "streaming-data-rows",
    name: "Streaming Data Rows",
    slug: "streaming-data-rows",
    description:
      "A live operational table your app drives - animated row insert, update, resort with continuity, per-cell change emphasis (▲▼, never color alone), numeric morphs, and status transitions. Not a data-grid.",
    category: "data-motion",
    subcategory: "Data motion",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["table", "streaming", "live data", "rows", "dashboard", "sort", "realtime", "orders"],
    registryItem: "streaming-data-rows",
    documentationPath: "/components/streaming-data-rows",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "luminous-topography",
    name: "Luminous Topography",
    slug: "luminous-topography",
    description:
      "Layered topographic contours that flow around focal regions and thin over a readable safe area, with a slow travelling light. Deterministic SVG + CSS, SSR- and reduced-motion-safe.",
    category: "backgrounds",
    subcategory: "Backgrounds",
    status: "beta",
    access: "free",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["background", "topography", "contours", "hero", "svg", "ambient"],
    registryItem: "luminous-topography",
    documentationPath: "/components/luminous-topography",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "canvas",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "workflow-topology-field",
    name: "Workflow Topology Field",
    slug: "workflow-topology-field",
    description:
      "An atmospheric background that draws your workflow as a topology: an animated active path, settled completed paths, and failed nodes marked with a ring + glyph (never color alone). Density thins over a readable safe area. Deterministic SVG + CSS, SSR- and reduced-motion-safe.",
    category: "product-backgrounds",
    subcategory: "Product Backgrounds",
    status: "beta",
    access: "free",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["background", "workflow", "topology", "orchestration", "pipeline", "svg", "safe area"],
    registryItem: "workflow-topology-field",
    documentationPath: "/components/workflow-topology-field",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "canvas",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "queue-pulse-lanes",
    name: "Queue Pulse Lanes",
    slug: "queue-pulse-lanes",
    description:
      "A queue/throughput background: pulses flow through restrained lanes, congestion makes them denser and slower, completed work fades into a history band, and blocked/delayed lanes carry a non-color stop cap + glyph. Density thins over a readable safe area. Deterministic SVG + CSS.",
    category: "product-backgrounds",
    subcategory: "Product Backgrounds",
    status: "beta",
    access: "free",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["background", "queue", "throughput", "jobs", "pipeline", "workers", "svg"],
    registryItem: "queue-pulse-lanes",
    documentationPath: "/components/queue-pulse-lanes",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "canvas",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "adaptive-safe-zone-grid",
    name: "Adaptive Safe-Zone Grid",
    slug: "adaptive-safe-zone-grid",
    description:
      "A content-aware structural grid for heroes: it quiets inside one or many safe areas so foreground copy stays readable, while detail collects toward the frame edges. Optional perspective skew, highlighted cells, and a restrained accent shimmer. Deterministic SVG + CSS, SSR- and reduced-motion-safe.",
    category: "product-backgrounds",
    subcategory: "Product Backgrounds",
    status: "beta",
    access: "free",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["background", "grid", "safe area", "hero", "content-aware", "perspective", "svg"],
    registryItem: "adaptive-safe-zone-grid",
    documentationPath: "/components/adaptive-safe-zone-grid",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "canvas",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "runtime-signal-map",
    name: "Runtime Signal Map",
    slug: "runtime-signal-map",
    description:
      "An infrastructure background where signal packets move through your service topology with health + direction: requests enter at ingress, flow between services grouped into regions, and degraded/error paths are marked without color (dashed + slower/stalled + glyph). One canvas + one rAF loop; deterministic, offscreen-paused.",
    category: "product-backgrounds",
    subcategory: "Product Backgrounds",
    status: "beta",
    access: "pro",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["background", "infrastructure", "signals", "observability", "services", "canvas", "topology"],
    registryItem: "runtime-signal-map",
    documentationPath: "/components/runtime-signal-map",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "canvas",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "event-propagation-matrix",
    name: "Event Propagation Matrix",
    slug: "event-propagation-matrix",
    description:
      "A temporal background where events propagate through a structured cell matrix - origin cells light, then neighbors along the grid, so waves step cell-to-cell (not free-space circles). Overlaps damp, failed propagation halts with a non-color glyph, and old events settle into a quiet history layer. Deterministic SVG + CSS.",
    category: "product-backgrounds",
    subcategory: "Product Backgrounds",
    status: "beta",
    access: "pro",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["background", "events", "propagation", "webhooks", "audit", "matrix", "svg"],
    registryItem: "event-propagation-matrix",
    documentationPath: "/components/event-propagation-matrix",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "canvas",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "data-contour-surface",
    name: "Data Contour Surface",
    slug: "data-contour-surface",
    description:
      "A data-driven contour background: contours are computed from your values (signed pressure points, thresholds, active/comparison regions) via canvas marching-squares - not a random texture. Emphasized thresholds get heavier bands, the active region brightens, comparisons ghost, and data changes ease smoothly. Deterministic, offscreen-paused.",
    category: "product-backgrounds",
    subcategory: "Product Backgrounds",
    status: "beta",
    access: "pro",
    dependencies: [],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["background", "contours", "data", "analytics", "metrics", "canvas", "thresholds"],
    registryItem: "data-contour-surface",
    documentationPath: "/components/data-contour-surface",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "canvas",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "agent-operations-hero",
    name: "Agent Operations Hero",
    slug: "agent-operations-hero",
    description:
      "An editable hero block for AI/automation products: a real agent workflow (run timeline, prompt input, one active tool, one source) with outcome copy + CTAs, across idle/running/tool-active/waiting/completed/failed. App-controlled - never simulates a model.",
    category: "workflow-heroes",
    subcategory: "Workflow Heroes",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/agent-run-timeline`,
      `${product.registryNamespace}/prompt-composer`,
      `${product.registryNamespace}/tool-call-activity`,
      `${product.registryNamespace}/source-citation-rail`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "hero", "ai", "agent", "orchestration", "workflow"],
    registryItem: "agent-operations-hero",
    documentationPath: "/components/agent-operations-hero",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["agent-run-timeline", "prompt-composer", "tool-call-activity", "source-citation-rail"],
  },
  {
    id: "deployment-control-hero",
    name: "Deployment Control Hero",
    slug: "deployment-control-hero",
    description:
      "An editable hero block for developer-tool/infra products: a real deployment control surface (selected env, four pipeline stages, a short log, one request result) with outcome copy + CTAs, across ready/deploying/validating/failed/retrying/completed. Provider-neutral demo data.",
    category: "workflow-heroes",
    subcategory: "Workflow Heroes",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/environment-switcher`,
      `${product.registryNamespace}/deployment-pipeline`,
      `${product.registryNamespace}/live-log-stream`,
      `${product.registryNamespace}/api-request-inspector`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "hero", "deployment", "devtools", "ci", "infrastructure"],
    registryItem: "deployment-control-hero",
    documentationPath: "/components/deployment-control-hero",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["environment-switcher", "deployment-pipeline", "live-log-stream", "api-request-inspector"],
  },
  {
    id: "live-data-command-hero",
    name: "Live Data Command Hero",
    slug: "live-data-command-hero",
    description:
      "An editable hero block for operational-data products, centered on continuity and changing state: three morphing metrics, a refresh state, a small live-data subset, and one active filter - with outcome copy + CTAs, across initial/live/filtering/refreshing/partial/stale/error/recovery.",
    category: "workflow-heroes",
    subcategory: "Workflow Heroes",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/kpi-number-morph`,
      `${product.registryNamespace}/data-refresh-state`,
      `${product.registryNamespace}/streaming-data-rows`,
      `${product.registryNamespace}/filter-result-transition`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "hero", "live data", "metrics", "operational", "streaming"],
    registryItem: "live-data-command-hero",
    documentationPath: "/components/live-data-command-hero",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["kpi-number-morph", "data-refresh-state", "streaming-data-rows", "filter-result-transition"],
  },
  {
    id: "collaborative-launch-hero",
    name: "Collaborative Launch Hero",
    slug: "collaborative-launch-hero",
    description:
      "An editable hero block for collaboration/review products: people active, a review underway, and one pending decision (presence, typing, approval, comment, activity) with outcome copy + CTAs, across review-open/commenting/changes-requested/approval-pending/approved/rejected/resolved.",
    category: "workflow-heroes",
    subcategory: "Workflow Heroes",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/live-presence-stack`,
      `${product.registryNamespace}/typing-and-presence`,
      `${product.registryNamespace}/approval-workflow`,
      `${product.registryNamespace}/comment-thread`,
      `${product.registryNamespace}/activity-stream`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "hero", "collaboration", "review", "approval", "presence"],
    registryItem: "collaborative-launch-hero",
    documentationPath: "/components/collaborative-launch-hero",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["live-presence-stack", "typing-and-presence", "approval-workflow", "comment-thread", "activity-stream"],
  },
  {
    id: "source-citation-rail",
    name: "Source Citation Rail",
    slug: "source-citation-rail",
    description:
      "Sync inline [n] citation markers with a source rail: active highlight, expandable excerpts, copy link, open-source callback, keyboard nav, and rail/list/card layouts.",
    category: "ai",
    subcategory: "AI interfaces",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["ai", "citations", "sources", "research", "references", "attribution", "rail"],
    registryItem: "source-citation-rail",
    documentationPath: "/components/source-citation-rail",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "api-request-inspector",
    name: "API Request Inspector",
    slug: "api-request-inspector",
    description:
      "A presentation-only inspector for one HTTP exchange - method/url/status/duration, headers/query/body, timing phases, error, retryCount, auth summary. Secrets are redacted by default and never leak into the DOM, search, or copies. It never sends anything.",
    category: "developer-tools",
    subcategory: "Developer tools",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["api", "requests", "http", "webhooks", "inspector", "headers", "redaction", "devtools", "observability"],
    registryItem: "api-request-inspector",
    documentationPath: "/components/api-request-inspector",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "approval-workflow",
    name: "Approval Workflow",
    slug: "approval-workflow",
    description:
      "Present and control an app-owned approval process - sequential + parallel (any-one / quorum) stages, minimum approvals, required vs optional reviewers, current-user action state, and decision history. Your app owns authorization; the component surfaces the disabled reason.",
    category: "collaboration",
    subcategory: "Collaboration",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["approval", "review", "workflow", "sign-off", "reviewers", "stages", "collaboration", "decision"],
    registryItem: "approval-workflow",
    documentationPath: "/components/approval-workflow",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "filter-result-transition",
    name: "Filter Result Transition",
    slug: "filter-result-transition",
    description:
      "A transition layer for filtered/searched collections - cards enter, leave, and reorder with continuity, the result count morphs, and empty/loading/error states cross-fade. Keeps keyboard focus sane via a focus-fallback contract. Not a data table.",
    category: "data-motion",
    subcategory: "Data motion",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["filter", "search", "results", "transition", "faceted", "collection", "empty state", "reorder"],
    registryItem: "filter-result-transition",
    documentationPath: "/components/filter-result-transition",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "swipe-action-row",
    name: "Swipe Action Row",
    slug: "swipe-action-row",
    description:
      "A mobile-first swipe-to-reveal action row that is never touch-only - actions are reachable by drag, Tab-to-focus reveal, and an overflow menu. Destructive actions require a confirm, full-swipe is opt-in, and grouped rows keep only one open.",
    category: "mobile",
    subcategory: "Mobile interactions",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["swipe", "mobile", "gestures", "list", "actions", "touch", "keyboard", "undo"],
    registryItem: "swipe-action-row",
    documentationPath: "/components/swipe-action-row",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "agent-run-timeline",
    name: "Agent Run Timeline",
    slug: "agent-run-timeline",
    description:
      "Presentation-only timeline for a multi-step agent run - ordered steps with tool calls, outputs, retries, nested stages, approvals, and run controls. The app owns the run.",
    category: "ai",
    subcategory: "AI interfaces",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["ai", "agent", "timeline", "run", "steps", "approval", "orchestration", "retry", "status"],
    registryItem: "agent-run-timeline",
    documentationPath: "/components/agent-run-timeline",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "environment-switcher",
    name: "Environment Switcher",
    slug: "environment-switcher",
    description:
      "Choose the environment an app targets - dev / staging / production, regions, preview branches - from a searchable, keyboard-navigable listbox with status/health, disabled reasons, recents + favorites. Production switches are labelled and can require confirmation. It never touches a real backend.",
    category: "developer-tools",
    subcategory: "Developer tools",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["environment", "staging", "production", "region", "devtools", "deploy", "switcher", "branch", "preview"],
    registryItem: "environment-switcher",
    documentationPath: "/components/environment-switcher",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "comment-thread",
    name: "Comment Thread",
    slug: "comment-thread",
    description:
      "A production comment thread - nested replies, mentions, reactions, edit, resolve/reopen, and optimistic send (pending → sent, failed → retry, focus preserved). Your app owns persistence + permissions.",
    category: "collaboration",
    subcategory: "Collaboration",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["comments", "thread", "review", "replies", "mentions", "reactions", "collaboration"],
    registryItem: "comment-thread",
    documentationPath: "/components/comment-thread",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "data-refresh-state",
    name: "Data Refresh State",
    slug: "data-refresh-state",
    description:
      "A rich refresh indicator your app drives - idle, checking, refreshing (determinate or honestly-indeterminate), partially updated, success, stale, offline, error, paused, cancelled - with manual refresh, cancel, retry, pause/resume, and interval controls. Never spins on idle; never fakes progress.",
    category: "data-motion",
    subcategory: "Data motion",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["refresh", "sync", "stale", "offline", "polling", "data", "dashboard", "revalidate"],
    registryItem: "data-refresh-state",
    documentationPath: "/components/data-refresh-state",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "mobile-filter-sheet",
    name: "Mobile Filter Sheet",
    slug: "mobile-filter-sheet",
    description:
      "A real mobile filter workflow - app-defined groups (checkbox, radio, range, date, search, hierarchical, custom), a draft-vs-applied model with Apply/Cancel/Reset/Clear, a live announced result count, chips, and a bottom-sheet / fullscreen / desktop-panel surface. Focus-trapped, 200%-zoom-safe, never gesture-only.",
    category: "mobile",
    subcategory: "Mobile interactions",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["filter", "sheet", "mobile", "facets", "bottom sheet", "drawer", "search", "range", "checkbox"],
    registryItem: "mobile-filter-sheet",
    documentationPath: "/components/mobile-filter-sheet",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "prompt-composer",
    name: "Prompt Composer",
    slug: "prompt-composer",
    description:
      "A production prompt-composition surface - multiline draft, {{variable}} insertion, app-supplied attachments/templates/models, an honest app-owned token budget, and Send/Stop/Retry across idle/loading/streaming/error. Never calls a model or sends anything.",
    category: "ai",
    subcategory: "AI interfaces",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["ai", "prompt", "composer", "llm", "input", "attachments", "variables", "template", "tokens"],
    registryItem: "prompt-composer",
    documentationPath: "/components/prompt-composer",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "webhook-event-stream",
    name: "Webhook Event Stream",
    slug: "webhook-event-stream",
    description:
      "A console for an app-owned stream of outbound webhook deliveries - animated arrival, per-delivery status (icon+text), retry counts, response codes, expandable redacted payload/header inspection, filter, search, retry/replay callbacks, and non-fighting pause & follow. Secrets are redacted and never enter the DOM, search, or copies.",
    category: "developer-tools",
    subcategory: "Developer tools",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["webhooks", "events", "delivery", "devtools", "retry", "replay", "redaction", "stream", "observability"],
    registryItem: "webhook-event-stream",
    documentationPath: "/components/webhook-event-stream",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "mention-suggestions",
    name: "Mention Suggestions",
    slug: "mention-suggestions",
    description:
      "A fully-controlled @-mention suggestion popup - the app owns the editable field and text insertion; the component renders an accessible, keyboard-navigable listbox of people/teams and drives selection, keeping DOM focus in the app's input via the ARIA combobox + aria-activedescendant pattern.",
    category: "collaboration",
    subcategory: "Collaboration",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["mentions", "suggestions", "collaboration", "autocomplete", "combobox", "people", "typeahead"],
    registryItem: "mention-suggestions",
    documentationPath: "/components/mention-suggestions",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "data-quality-status",
    name: "Data Quality Status",
    slug: "data-quality-status",
    description:
      "A data-quality panel that displays app-supplied freshness/completeness/accuracy metrics (rendering \"Unknown\" when unmeasured), a filterable list of validation checks with keyboard-expandable per-check issue lists, affected-record counts, last-checked time, and a retry-validation control. Status is icon + text; it never claims accuracy without supplied evidence.",
    category: "data-motion",
    subcategory: "Data motion",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["data quality", "validation", "freshness", "completeness", "accuracy", "checks", "monitoring", "data"],
    registryItem: "data-quality-status",
    documentationPath: "/components/data-quality-status",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "keyboard-safe-form",
    name: "Keyboard-safe Form",
    slug: "keyboard-safe-form",
    description:
      "A mobile form whose sticky Submit/Cancel bar rides above the virtual keyboard via the VisualViewport API (degrading to a plain sticky footer where unavailable), with an aria-linked validation summary, cancellable async submission, and an unsaved-changes discard guard. The app owns the fields and submission.",
    category: "mobile",
    subcategory: "Mobile interactions",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["form", "mobile", "keyboard", "virtual keyboard", "safe area", "validation", "async", "sticky"],
    registryItem: "keyboard-safe-form",
    documentationPath: "/components/keyboard-safe-form",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "file-upload-pipeline",
    name: "File Upload Pipeline",
    slug: "file-upload-pipeline",
    description:
      "An application-controlled file upload workflow - app-supplied items with progress, pause/resume/retry/cancel/remove, processing stages, and empty/drag-over/partial-failure/offline states. Never uploads bytes itself unless given an adapter; status by icon+text; progress announcements throttled.",
    category: "file",
    subcategory: "File workflows",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["file", "upload", "dropzone", "progress", "queue", "retry", "resumable", "files"],
    registryItem: "file-upload-pipeline",
    documentationPath: "/components/file-upload-pipeline",
    dateAdded: ADDED,
    featured: true,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "product-variant-selector",
    name: "Product Variant Selector",
    slug: "product-variant-selector",
    description:
      "A production variant selector (color/size/material/plan/bundle/custom) - controlled selection, dependent options, app-supplied availability + inventory + unavailable combinations, animated-but-text-backed price adjustments, and a mobile compact layout. No fabricated scarcity or discounts.",
    category: "commerce",
    subcategory: "Commerce",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["commerce", "variant", "product", "options", "swatch", "price", "inventory", "radiogroup"],
    registryItem: "product-variant-selector",
    documentationPath: "/components/product-variant-selector",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "passkey-setup-flow",
    name: "Passkey Setup Flow",
    slug: "passkey-setup-flow",
    description:
      "A presentation + orchestration layer for passkey (WebAuthn) setup - the app supplies WebAuthn operations and results; the component renders intro/capability/naming/system-prompt/success/failure/existing-credential/unsupported states, always keeps an alternative sign-in path, and never implements crypto, collects key material, or fakes success.",
    category: "security",
    subcategory: "Security & accounts",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["security", "passkey", "webauthn", "2fa", "authentication", "account", "login", "mfa"],
    registryItem: "passkey-setup-flow",
    documentationPath: "/components/passkey-setup-flow",
    dateAdded: ADDED,
    featured: true,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "message-delivery-states",
    name: "Message Delivery States",
    slug: "message-delivery-states",
    description:
      "A message list with an honest delivery-receipt layer for chat/support/collaboration - draft/sending/sent/delivered/read/failed/retrying/scheduled/cancelled/edited as icon+text, read receipts, associated errors, retry/cancel/edit/copy. The app owns delivery; no network simulation and no constant idle animation.",
    category: "communication",
    subcategory: "Communication",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["communication", "chat", "message", "delivery", "read receipt", "retry", "status", "messaging"],
    registryItem: "message-delivery-states",
    documentationPath: "/components/message-delivery-states",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "kanban-card-movement",
    name: "Kanban Card Movement",
    slug: "kanban-card-movement",
    description:
      "An application-controlled Kanban interaction layer - pointer + touch + keyboard/menu card movement, drop validation, optimistic move with failure rollback, drop indicators, and empty columns. Dragging is never required. Clean-room (no external drag library); transform-based movement that doesn't re-render every card.",
    category: "productivity",
    subcategory: "Productivity",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["productivity", "kanban", "board", "drag", "dnd", "cards", "columns", "keyboard", "optimistic"],
    registryItem: "kanban-card-movement",
    documentationPath: "/components/kanban-card-movement",
    dateAdded: ADDED,
    featured: true,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "multi-file-queue",
    name: "Multi-file Queue",
    slug: "multi-file-queue",
    description:
      "A queue MANAGER for a collection of files/jobs - priority lanes, concurrency-slot occupancy, blocked-item explanation, queue-level progress, per-item reorder + priority, and pause-all/resume-all/retry-failed/clear-completed. Distinct from File Upload Pipeline; never uploads internally.",
    category: "file",
    subcategory: "File workflows",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["queue", "batch", "upload", "processing", "files", "priority", "concurrency", "media"],
    registryItem: "multi-file-queue",
    documentationPath: "/components/multi-file-queue",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "cart-item-transition",
    name: "Cart Item Transition",
    slug: "cart-item-transition",
    description:
      "An app-controlled animated cart line item - arrival, quantity/total morph, variant crossfade, price-change, limited/unavailable, removal → Undo → restore, with optimistic mutation + automatic rollback and honest failed/Retry. Price/inventory are app-owned; no manipulative urgency.",
    category: "commerce",
    subcategory: "Commerce",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["cart", "quantity", "checkout", "purchase", "product", "variant", "price", "order"],
    registryItem: "cart-item-transition",
    documentationPath: "/components/cart-item-transition",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "two-factor-setup-flow",
    name: "Two-Factor Setup Flow",
    slug: "two-factor-setup-flow",
    description:
      "Orchestration + presentation for adding a second auth factor (authenticator/security-key/SMS/email/recovery-codes/custom). The app supplies all operations + state; the component never implements crypto, shows real secrets, stores codes, or claims the account is secure because setup finished. Recovery codes are sensitive; an alternative is always offered.",
    category: "security",
    subcategory: "Security & accounts",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["two-factor", "2fa", "authenticator", "security", "mfa", "recovery-codes", "account", "setup"],
    registryItem: "two-factor-setup-flow",
    documentationPath: "/components/two-factor-setup-flow",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "typing-and-presence",
    name: "Typing and Presence",
    slug: "typing-and-presence",
    description:
      "A combined real-time typing + participant-presence strip - presence (online/active/idle/away/offline/reconnecting) + typing by shape+text, avatar initials, an overflow summary (\"Three people are typing\"), and compact/inline/floating modes. App supplies all data; a debounced live region avoids keystroke spam; ambient motion pauses when hidden.",
    category: "communication",
    subcategory: "Communication",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["typing", "presence", "thread", "messaging", "conversation", "collaboration", "status"],
    registryItem: "typing-and-presence",
    documentationPath: "/components/typing-and-presence",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "medium",
    releaseStatus: "released",
  },
  {
    id: "task-dependency-map",
    name: "Task Dependency Map",
    slug: "task-dependency-map",
    description:
      "An app-controlled task dependency visualization (not a graph editor) - deterministic dependency-depth layout with static SVG lines, blocked/blocking relationships, prerequisite + dependent inspection, highlighted active path, app-supplied cycle error, status filter, and a compact list/mobile fallback. Keyboard-first (dragging never required); optimistic move with rollback.",
    category: "productivity",
    subcategory: "Productivity",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["dependency", "blocked", "project", "planning", "tasks", "graph", "milestone", "roadmap"],
    registryItem: "task-dependency-map",
    documentationPath: "/components/task-dependency-map",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "processing-timeline",
    name: "Processing Timeline",
    slug: "processing-timeline",
    description:
      "A timeline for ONE ingested item moving through multiple app-owned processing stages (scan → transcode → thumbnail → caption → publish) - per-stage status/progress/output/logs/warnings/errors, current-stage focus, expansion, retry/skip/cancel/restart, duration summary, and vertical/horizontal layouts. Distinct from Upload Pipeline + Multi-file Queue; never fakes progress.",
    category: "file",
    subcategory: "File workflows",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["processing", "pipeline", "stages", "encoding", "transcode", "files", "media", "job"],
    registryItem: "processing-timeline",
    documentationPath: "/components/processing-timeline",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "checkout-progress",
    name: "Checkout Progress",
    slug: "checkout-progress",
    description:
      "An app-controlled multi-step checkout progress/orchestration surface (not a payment processor) - current + completed + editable steps, per-step validation + blocked reasons, async step save, return-to-previous, error/progress summaries, a sticky order-summary slot, and optional guest/account modes. Never collects or processes payment; no fake processing progress.",
    category: "commerce",
    subcategory: "Commerce",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["checkout", "steps", "commerce", "purchase", "booking", "subscription", "wizard", "order"],
    registryItem: "checkout-progress",
    documentationPath: "/components/checkout-progress",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "session-security-center",
    name: "Session Security Center",
    slug: "session-security-center",
    description:
      "A presentation + control surface for reviewing and revoking active account sessions - device/browser/OS, app-supplied approximate location + IP summary + trust/risk labels, current-session identification, single + bulk revocation with confirmation (current session preserved), rename/trust, filter/sort, and honest failed-revocation + retry. The app owns revocation; never labels a session compromised without app data.",
    category: "security",
    subcategory: "Security & accounts",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["session", "security", "account", "device", "revoke", "trust", "login", "sessions"],
    registryItem: "session-security-center",
    documentationPath: "/components/session-security-center",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "thread-expansion",
    name: "Thread Expansion",
    slug: "thread-expansion",
    description:
      "A navigation + expansion surface for deeply nested discussions - expand/collapse branches, jump to next unread branch, go-to-parent, selected-path breadcrumb, collapse-resolved, deleted-reply placeholder, and lazy reply loading (loading/error/retry/load-more). An accessible tree, depth-capped so pathological threads never render unbounded. Distinct from Comment Thread.",
    category: "communication",
    subcategory: "Communication",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["thread", "replies", "unread", "conversation", "messaging", "nested", "tree"],
    registryItem: "thread-expansion",
    documentationPath: "/components/thread-expansion",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "project-timeline",
    name: "Project Timeline",
    slug: "project-timeline",
    description:
      "An app-controlled, time-scaled project timeline (not a Gantt/charting library) - milestones/phases/tasks/releases/events on a day/week/month axis, a current-date marker (from a today prop), horizontal nav + jump-to-today, phase collapse, item selection with textual date ranges, dependency indication, status filtering, a structured list/mobile fallback, and a non-drag keyboard reschedule (optimistic + rollback). No scheduling algorithms; the app owns dates.",
    category: "productivity",
    subcategory: "Productivity",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`, `${product.registryNamespace}/primitives`],
    tags: ["timeline", "roadmap", "project", "milestone", "planning", "gantt", "schedule"],
    registryItem: "project-timeline",
    documentationPath: "/components/project-timeline",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
  },
  {
    id: "ai-agent-workspace",
    name: "AI Agent Workspace",
    slug: "ai-agent-workspace",
    description:
      "A composed AI agent workspace block: run timeline, tool-call activity, a streamed answer, and interactive source citations - app-controlled, never simulates a model.",
    category: "ai",
    subcategory: "AI interfaces",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/agent-run-timeline`,
      `${product.registryNamespace}/tool-call-activity`,
      `${product.registryNamespace}/ai-response-stream`,
      `${product.registryNamespace}/source-citation-rail`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "ai", "agent", "workspace"],
    registryItem: "ai-agent-workspace",
    documentationPath: "/components/ai-agent-workspace",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["agent-run-timeline", "tool-call-activity", "ai-response-stream", "source-citation-rail"],
  },
  {
    id: "deployment-command-center",
    name: "Deployment Command Center",
    slug: "deployment-command-center",
    description:
      "A composed deploy console block - Environment Switcher, Deployment Pipeline, Live Log Stream, and API Request Inspector wired to one app-owned demo state machine across deploying, following logs, failure, retry, and completion. Provider-neutral demo data.",
    category: "developer-tools",
    subcategory: "Developer tools",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/environment-switcher`,
      `${product.registryNamespace}/deployment-pipeline`,
      `${product.registryNamespace}/live-log-stream`,
      `${product.registryNamespace}/api-request-inspector`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "deployment", "devtools", "console"],
    registryItem: "deployment-command-center",
    documentationPath: "/components/deployment-command-center",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["environment-switcher", "deployment-pipeline", "live-log-stream", "api-request-inspector"],
  },
  {
    id: "collaborative-review-workspace",
    name: "Collaborative Review Workspace",
    slug: "collaborative-review-workspace",
    description:
      "A composed review screen - live presence, an app-owned approval workflow, the discussion thread, and an activity rail wired into one demo state machine. Approving advances the workflow and records activity; new comments appear in the thread and the feed.",
    category: "collaboration",
    subcategory: "Collaboration",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/live-presence-stack`,
      `${product.registryNamespace}/approval-workflow`,
      `${product.registryNamespace}/comment-thread`,
      `${product.registryNamespace}/activity-stream`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "collaboration", "review", "approval"],
    registryItem: "collaborative-review-workspace",
    documentationPath: "/components/collaborative-review-workspace",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["live-presence-stack", "approval-workflow", "comment-thread", "activity-stream"],
  },
  {
    id: "live-operations-dashboard",
    name: "Live Operations Dashboard",
    slug: "live-operations-dashboard",
    description:
      "A composed ops dashboard block - morphing KPI stats with a refresh-state control, a filterable service grid, and a live streaming table, wired to one demo state machine across loading, live, filtered, refreshing, partial, stale, error, and recovery.",
    category: "data-motion",
    subcategory: "Data motion",
    status: "beta",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [
      `${product.registryNamespace}/kpi-number-morph`,
      `${product.registryNamespace}/data-refresh-state`,
      `${product.registryNamespace}/filter-result-transition`,
      `${product.registryNamespace}/streaming-data-rows`,
      `${product.registryNamespace}/utils`,
      `${product.registryNamespace}/primitives`,
    ],
    tags: ["block", "dashboard", "data", "operations"],
    registryItem: "live-operations-dashboard",
    documentationPath: "/components/live-operations-dashboard",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
    complexity: "complex",
    releaseStatus: "released",
    kind: "block",
    composes: ["kpi-number-morph", "data-refresh-state", "filter-result-transition", "streaming-data-rows"],
  },
  {
    id: "animated-dialog",
    name: "Animated Dialog",
    slug: "animated-dialog",
    description: "A Radix dialog with animated overlay, scale/slide content, and clean exit - focus trap and Esc preserved.",
    category: "animated-shadcn",
    status: "stable",
    access: "free",
    dependencies: ["motion", "@radix-ui/react-dialog"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["dialog", "modal", "overlay", "radix"],
    registryItem: "animated-dialog",
    documentationPath: "/components/animated-dialog",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion+radix",
    stage: "interactive",
  },
  {
    id: "animated-tabs",
    name: "Animated Tabs",
    slug: "animated-tabs",
    description: "Radix tabs with a shared-layout indicator that morphs between tabs and direction-aware content transitions.",
    category: "animated-shadcn",
    status: "stable",
    access: "free",
    dependencies: ["motion", "@radix-ui/react-tabs"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["tabs", "navigation", "radix", "layout"],
    registryItem: "animated-tabs",
    documentationPath: "/components/animated-tabs",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion+radix",
    stage: "interactive",
  },
  {
    id: "animated-accordion",
    name: "Animated Accordion",
    slug: "animated-accordion",
    description: "Radix accordion animating height, opacity, and chevron - single/multiple modes and keyboard preserved.",
    category: "animated-shadcn",
    status: "stable",
    access: "free",
    dependencies: ["motion", "@radix-ui/react-accordion"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["accordion", "disclosure", "radix"],
    registryItem: "animated-accordion",
    documentationPath: "/components/animated-accordion",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion+radix",
    stage: "interactive",
  },
  {
    id: "animated-button",
    name: "Animated Button",
    slug: "animated-button",
    description: "A real button with press feedback, accessible loading and success states - focus-visible and forms preserved.",
    category: "animated-shadcn",
    status: "stable",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["button", "cta", "loading"],
    registryItem: "animated-button",
    documentationPath: "/components/animated-button",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "interactive",
  },
  {
    id: "kinetic-emphasis",
    name: "Kinetic Emphasis",
    slug: "kinetic-emphasis",
    description:
      "Reading emphasis that travels through the copy - a sweep activates each word and marked <em> phrases ignite into persistent designed typography. Final state renders on the server.",
    category: "text",
    subcategory: "signature",
    status: "beta",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["text", "emphasis", "headline", "kinetic", "signature", "typography"],
    registryItem: "kinetic-emphasis",
    documentationPath: "/components/kinetic-emphasis",
    dateAdded: ADDED,
    // Independently Strongly Sellable (2026-07-14 premium re-review) — homepage-eligible.
    featured: true,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "text",
  },
  {
    id: "blur-text",
    name: "Blur Text",
    slug: "blur-text",
    description: "Reveals text segment-by-segment with a de-blur and drift. Full string exposed to screen readers once.",
    category: "text",
    status: "stable",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["text", "reveal", "blur", "hero", "headline"],
    registryItem: "blur-text",
    documentationPath: "/components/blur-text",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "text",
  },
  {
    id: "rotating-text",
    name: "Rotating Text",
    slug: "rotating-text",
    description: "Cycles words or phrases with enter/exit, pauses on hover/focus, and announces the current word politely.",
    category: "text",
    status: "stable",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["text", "rotating", "loop", "hero"],
    registryItem: "rotating-text",
    documentationPath: "/components/rotating-text",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "text",
  },
  {
    id: "animated-list",
    name: "Animated List",
    slug: "animated-list",
    description: "Adds, removes, and reorders list items with staggered enter/exit that never steals keyboard focus.",
    category: "creative",
    status: "stable",
    access: "pro",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["list", "stagger", "presence", "notifications"],
    registryItem: "animated-list",
    documentationPath: "/components/animated-list",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "card",
  },
  {
    id: "spotlight-card",
    name: "Spotlight Card",
    slug: "spotlight-card",
    description: "A surface with a pointer-following radial glow. CSS-only tracking, no re-render, graceful on touch.",
    category: "creative",
    status: "stable",
    access: "pro",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["card", "spotlight", "glow", "pointer", "pricing"],
    registryItem: "spotlight-card",
    documentationPath: "/components/spotlight-card",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "css",
    stage: "card",
  },
  {
    id: "animated-grid",
    name: "Animated Grid",
    slug: "animated-grid",
    description: "A subtle, CSS-only moving grid backdrop with a radial fade. Stops under reduced motion, no JS loop.",
    category: "backgrounds",
    status: "stable",
    access: "free",
    dependencies: ["clsx", "tailwind-merge"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["background", "grid", "ambient", "css"],
    registryItem: "animated-grid",
    documentationPath: "/components/animated-grid",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: false,
    animationEngine: "css",
    stage: "canvas",
  },
  {
    id: "animated-icons",
    name: "Animated Icons",
    slug: "animated-icons",
    description: "Arrow and Copy icons that animate on hover/tap/focus. Decorative and never separately focusable.",
    category: "icons",
    status: "stable",
    access: "free",
    dependencies: ["motion"],
    registryDependencies: [`${product.registryNamespace}/utils`],
    tags: ["icons", "arrow", "copy", "lucide-style"],
    registryItem: "animated-icons",
    documentationPath: "/components/animated-icons",
    dateAdded: ADDED,
    featured: false,
    supportsDarkMode: true,
    supportsReducedMotion: true,
    requiresClient: true,
    animationEngine: "motion",
    stage: "icon",
  },
];

// ---- derived helpers (used by nav/search/filters/cards/pages) ----

export const bySlug = new Map(catalog.map((c) => [c.slug, c]));

export function categoryCount(id: CategoryId): number {
  return catalog.filter((c) => c.category === id).length;
}

export function itemsByCategory(id: CategoryId): CatalogItem[] {
  return catalog.filter((c) => c.category === id);
}

export function featuredItems(): CatalogItem[] {
  return catalog.filter((c) => c.featured);
}

/** Entry-kind helpers. Absent `kind` means a plain component. */
export const kindOf = (c: CatalogItem): "component" | "block" | "pack" => c.kind ?? "component";
export function componentItems(): CatalogItem[] {
  return catalog.filter((c) => kindOf(c) === "component");
}
export function blockItems(): CatalogItem[] {
  return catalog.filter((c) => kindOf(c) === "block");
}
export function packItems(): CatalogItem[] {
  return catalog.filter((c) => kindOf(c) === "pack");
}

export function recentItems(limit = 8): CatalogItem[] {
  return [...catalog].sort((a, b) => b.dateAdded.localeCompare(a.dateAdded)).slice(0, limit);
}

/** Lightweight search over name/description/tags/category. */
export function searchCatalog(query: string): CatalogItem[] {
  const q = query.trim().toLowerCase();
  if (!q) return catalog;
  return catalog.filter((c) =>
    [c.name, c.description, c.category, ...c.tags].join(" ").toLowerCase().includes(q),
  );
}

export function itemInstall(item: CatalogItem): string {
  return installCommand(item.registryItem);
}

export const accessLabel: Record<Access, string> = {
  free: product.freeTierLabel,
  pro: product.premiumTierLabel,
};

// ---- catalog presentation resolution (docs/55) ----

/** Category → default surface family + size + span. Individual items override. */
const CATEGORY_PRESENTATION: Record<
  CategoryId,
  { family: StageFamily; size: PreviewSize; span: CardSpan }
> = {
  ai: { family: "ai", size: "standard", span: 6 },
  "developer-tools": { family: "console", size: "standard", span: 6 },
  collaboration: { family: "collab", size: "standard", span: 6 },
  "data-motion": { family: "data", size: "standard", span: 6 },
  mobile: { family: "mobile", size: "mobile", span: 4 },
  file: { family: "console", size: "standard", span: 6 },
  commerce: { family: "commerce", size: "standard", span: 6 },
  security: { family: "security", size: "standard", span: 6 },
  communication: { family: "collab", size: "standard", span: 6 },
  productivity: { family: "productivity", size: "wide", span: 8 },
  "animated-shadcn": { family: "neutral", size: "standard", span: 6 },
  text: { family: "editorial", size: "standard", span: 6 },
  creative: { family: "creative", size: "standard", span: 6 },
  backgrounds: { family: "creative", size: "ambient", span: 12 },
  "product-backgrounds": { family: "console", size: "ambient", span: 12 },
  "workflow-heroes": { family: "ai", size: "full", span: 12 },
  icons: { family: "neutral", size: "small", span: 4 },
};

const SIZE_SPAN: Record<PreviewSize, CardSpan> = {
  small: 4,
  standard: 6,
  wide: 8,
  full: 12,
  mobile: 4,
  ambient: 12,
};

/** Per-item curation — the deliberate exceptions that give strong components room. */
const PRESENTATION_OVERRIDES: Record<string, Partial<Presentation>> = {
  // Signature text — headline scale, deserves the full row.
  "kinetic-emphasis": { previewSize: "full", stageFamily: "editorial", cardSpan: 12 },
  "blur-text": { previewSize: "wide", stageFamily: "editorial", cardSpan: 8 },
  "rotating-text": { previewSize: "standard", stageFamily: "editorial", cardSpan: 6 },
  // Ambient backgrounds — full-bleed environments.
  "luminous-topography": { previewSize: "ambient", stageFamily: "creative", cardSpan: 12 },
  "workflow-topology-field": { previewSize: "ambient", stageFamily: "console", cardSpan: 12 },
  "queue-pulse-lanes": { previewSize: "ambient", stageFamily: "console", cardSpan: 12 },
  "adaptive-safe-zone-grid": { previewSize: "ambient", stageFamily: "neutral", cardSpan: 12 },
  "runtime-signal-map": { previewSize: "ambient", stageFamily: "console", cardSpan: 12 },
  "event-propagation-matrix": { previewSize: "ambient", stageFamily: "data", cardSpan: 12 },
  "data-contour-surface": { previewSize: "ambient", stageFamily: "data", cardSpan: 12 },
  "agent-operations-hero": { previewSize: "full", stageFamily: "ai", cardSpan: 12 },
  "deployment-control-hero": { previewSize: "full", stageFamily: "console", cardSpan: 12 },
  "live-data-command-hero": { previewSize: "full", stageFamily: "data", cardSpan: 12 },
  "collaborative-launch-hero": { previewSize: "full", stageFamily: "collab", cardSpan: 12 },
  "animated-grid": { previewSize: "ambient", stageFamily: "creative", cardSpan: 12 },
  // Complex AI/dev/data workflows — wide.
  "ai-response-stream": { previewSize: "wide", cardSpan: 8 },
  "tool-call-activity": { previewSize: "wide", cardSpan: 8 },
  "agent-run-timeline": { previewSize: "wide", cardSpan: 8 },
  "prompt-composer": { previewSize: "wide", cardSpan: 8 },
  "api-request-inspector": { previewSize: "wide", cardSpan: 8 },
  "streaming-data-rows": { previewSize: "full", cardSpan: 12 },
  "live-log-stream": { previewSize: "wide", cardSpan: 8 },
  "webhook-event-stream": { previewSize: "wide", cardSpan: 8 },
  // Large spatial productivity workspaces — full width.
  "task-dependency-map": { previewSize: "full", cardSpan: 12 },
  "project-timeline": { previewSize: "full", cardSpan: 12 },
  "kanban-card-movement": { previewSize: "full", cardSpan: 12 },
  // Collaboration workflow depth.
  "approval-workflow": { previewSize: "wide", cardSpan: 8 },
  "comment-thread": { previewSize: "wide", cardSpan: 8 },
  "thread-expansion": { previewSize: "wide", cardSpan: 8 },
  // Security centers read calmly at width.
  "session-security-center": { previewSize: "wide", cardSpan: 8 },
  // File pipelines.
  "processing-timeline": { previewSize: "wide", cardSpan: 8 },
  // Small primitives.
  "animated-button": { previewSize: "small", stageFamily: "neutral", cardSpan: 4 },
  "animated-icons": { previewSize: "small", stageFamily: "neutral", cardSpan: 4 },
  // Blocks & packs — always full-width workflow environments.
};

// Static span → responsive column classes (Tailwind needs literal class strings).
export const SPAN_CLASS: Record<CardSpan, string> = {
  4: "col-span-12 sm:col-span-6 lg:col-span-4",
  6: "col-span-12 sm:col-span-6 lg:col-span-6",
  8: "col-span-12 lg:col-span-8",
  12: "col-span-12",
};

/**
 * Row-packing (docs/57 §1). Greedy first-fit into 12-column rows; any leftover
 * columns are distributed to the smallest items in the row so every row sums to
 * exactly 12 — no lone 8-with-empty-4, no accidental holes. Full (12) items always
 * take their own row. Inputs are 4/6/12, so outputs are only ever 4, 6, or 12.
 */
export function packSpans(items: CatalogItem[]): Map<string, CardSpan> {
  const out = new Map<string, CardSpan>();
  let buf: string[] = [];
  let sum = 0;
  const flush = () => {
    if (buf.length === 0) return;
    const s = buf.map((id) => out.get(id)!) as number[];
    let leftover = 12 - sum;
    while (leftover > 0) {
      let mi = 0;
      for (let i = 1; i < s.length; i++) if (s[i] < s[mi]) mi = i;
      s[mi] += 1;
      leftover -= 1;
    }
    buf.forEach((id, i) => out.set(id, s[i] as CardSpan));
    buf = [];
    sum = 0;
  };
  for (const item of items) {
    const span = resolvePresentation(item).cardSpan;
    if (span >= 12) {
      flush();
      out.set(item.id, 12);
      continue;
    }
    if (sum + span > 12) flush();
    out.set(item.id, span);
    buf.push(item.id);
    sum += span;
  }
  flush();
  return out;
}

/** Resolve the effective catalog presentation for an item (defaults + overrides). */
export function resolvePresentation(item: CatalogItem): Presentation {
  const base = CATEGORY_PRESENTATION[item.category];
  const kind = kindOf(item);
  const override = PRESENTATION_OVERRIDES[item.id] ?? {};

  // Blocks/packs are always full-width workflow environments.
  const isEnvironment = kind === "block" || kind === "pack";

  // Complex components (not already curated) earn width — but never mobile/creative/
  // text/icon/shadcn items, whose surface is intentionally device/ambient/compact.
  const bumpEligible = !["mobile", "backgrounds", "product-backgrounds", "text", "creative", "icons", "animated-shadcn"].includes(
    item.category,
  );
  const complexityBump =
    item.complexity === "complex" && bumpEligible && !override.previewSize && !isEnvironment;

  const previewSize: PreviewSize =
    override.previewSize ?? (isEnvironment ? "full" : complexityBump ? "wide" : base.size);
  const stageFamily: StageFamily = override.stageFamily ?? base.family;
  const rawSpan: CardSpan = override.cardSpan ?? (isEnvironment ? 12 : SIZE_SPAN[previewSize] ?? base.span);
  // Grid-placement policy (docs/57): only 4 / 6 / 12 spans in the catalog. A lone
  // 8-col card leaves an un-fillable 4-col hole, so 8 collapses to 6 (pairs as 6+6)
  // — spatial/large/table/block items are already 12 via their overrides.
  const cardSpan: CardSpan = rawSpan === 8 ? 6 : rawSpan;
  const previewMode: PreviewMode =
    override.previewMode ?? (previewSize === "ambient" ? "ambient" : "staged");

  return { previewSize, previewMode, stageFamily, cardSpan, mobileCardSpan: 12 };
}
